import re

text = """
--------------------------------------------------------------------------------
1. AVES
--------------------------------------------------------------------------------

   Aves Congeladas:
   * Código: 52629  | ASA DE FGO FORMOSO CONG INDIVIDUAL (Cód. Interno: 529772)
   * Código: 97635  | ASA FRANGO CONG GUIBON KG (Cód. Interno: 97635)
   * Código: 22712  | CARCACA FGO CG NATTO KG (Cód. Interno: 2803)
   * Código: 20745  | CARCACA FGO CG SEARA KG (Cód. Interno: 2294)
   * Código: 35734  | CARNE MOIDA DE FGO FORTBOI CG 500G (Cód. Interno: não informado)
   * Código: 47677  | CORACAO FGO CG TEMP NATTO 600G (Cód. Interno: não informado)
   * Código: 97641  | CORACAO FRANGO CONG GUIBON SC 1KG (Cód. Interno: não informado)
   * Código: 71904  | COXA C SOB CONG GUIBON KG (Cód. Interno: 71904)
   * Código: 63298  | COXA C SOB DORSAL CANCAO ENV KG (Cód. Interno: 538981)
   * Código: 89964  | COXA C SOB DORSAL CONG GUIBON KG (Cód. Interno: 89964)
   * Código: 20266  | COXA C SOB FGO CG IND MAURICEA KG (Cód. Interno: 2007)
   * Código: 22863  | COXA C SOB FGO CG IND NATTO KG (Cód. Interno: 2732)
   * Código: 22693  | COXA C SOB FGO CG NATTO BD1KG (Cód. Interno: não informado)
   * Código: 52628  | COXA C SOB FGO FORMOSO CONG KG G (Cód. Interno: 529764)
   * Código: 52624  | COXA C.SOBRECOXA FGO FORMOSO BJ 1KG (Cód. Interno: não informado)
   * Código: 79045  | COXA CANCAO IQF 1KG (Cód. Interno: não informado)
   * Código: 19654  | COXA FGO CG ASSA F SADIA 800G (Cód. Interno: não informado)
   * Código: 20725  | COXA FGO CG ASSA F SEARA 800G (Cód. Interno: não informado)
   * Código: 21262  | COXA FGO CG IND MAURICEA PCT KG (Cód. Interno: 2322)
   * Código: 20090  | COXA FGO CG MAURICEA BD1KG (Cód. Interno: não informado)
   * Código: 11877  | COXA FGO CG MAURICEA IQF PCT 1KG (Cód. Interno: não informado)
   * Código: 22706  | COXA FGO CG NATTO BD1KG (Cód. Interno: não informado)
   * Código: 19649  | COXA FGO CG SADIA IQF PCT1KG (Cód. Interno: não informado)
   * Código: 20743  | COXA FGO CG SEARA BD1KG (Cód. Interno: não informado)
   * Código: 47058  | COXA FGO CG SEARA TEMP IQF 1KG (Cód. Interno: não informado)
   * Código: 20754  | COXA IQF SEARA 1KG (Cód. Interno: não informado)
   * Código: 37994  | COXIN ASA CG BUFFALO SEARA 800G (Cód. Interno: não informado)
   * Código: 34236  | COXIN ASA FGO CG NATTO 600G APIMENTADA (Cód. Interno: não informado)
   * Código: 22698  | COXIN ASA FGO CG NATTO BD1KG (Cód. Interno: não informado)
   * Código: 20746  | COXIN ASA FGO CG SEARA BD 1KG (Cód. Interno: não informado)
   * Código: 11865  | COXIN ASA FGO IQF MAURICEA PCT1KG CONG (Cód. Interno: não informado)
   * Código: 19614  | COXIN ASA FGO IQF SADIA PCT1KG CONG (Cód. Interno: não informado)
   * Código: 20756  | COXIN ASA FGO IQF SEARA PCT1KG (Cód. Interno: não informado)
   * Código: 37204  | COXIN ASA FGO SEARA EMPAN TRAD 400G (Cód. Interno: não informado)
   * Código: 79040  | COXINHA ASA CANCAO IQF 1KG (Cód. Interno: não informado)
   * Código: 97638  | COXINHA ASA DRUMET CGO GUIBON KG (Cód. Interno: 97638)
   * Código: 15698  | ESPETINHO CORACAO CONG JUNDIAI 430G TEMP (Cód. Interno: não informado)
   * Código: 22713  | ESPETINHO FGO BACON CG NATTO 800G (Cód. Interno: não informado)
   * Código: 22714  | ESPETINHO FGO CONG NATTO 800G TEMP (Cód. Interno: não informado)
   * Código: 42240  | ESPETO MED FGO CG TEMP JUNDIAI 500G (Cód. Interno: não informado)
   * Código: 15697  | ESPETO PEITO CG TEMP JUNDIAI 480G (Cód. Interno: não informado)
   * Código: 47074  | FGO CG S MIUDOS SEARA DAGRANJA KG (Cód. Interno: 47074)
   * Código: 22711  | FGO INT CG NATTO KG (Cód. Interno: 2802)
   * Código: 37989  | FGO INT CG TEMP PADARIA SEARA KG (Cód. Interno: 37989)
   * Código: 20727  | FGO INT CONG ASSA F SEARA KG (Cód. Interno: 3012)
   * Código: 37301  | FGO PASSARIN TEMP CG NATTO PCT 500G (Cód. Interno: não informado)
   * Código: 19589  | FGO PASSARIN TEMP CONG SADIA PCT1KG (Cód. Interno: não informado)
   * Código: 97649  | FIGAD FRANGO CONG GUIBON SC 1KG (Cód. Interno: não informado)
   * Código: 20255  | FIGADO FGO CG MAURICEA BD1KG (Cód. Interno: não informado)
   * Código: 22709  | FIGADO FGO CG NATTO BD1KG (Cód. Interno: não informado)
   * Código: 42384  | FILE COXA C SOB CG SEARA BD 1KG (Cód. Interno: não informado)
   * Código: 37997  | FILE COXA SOB CG SEARA LIM ERV 800G (Cód. Interno: não informado)
   * Código: 52601  | FILE DE PEITO CONG FGO FORMOSO 1KG (Cód. Interno: não informado)
   * Código: 37205  | FILE FGO A MILANESA CG SEARA 400G (Cód. Interno: não informado)
   * Código: 47069  | FILE PEIT CG SEARA DAGRANJA BD 600G (Cód. Interno: não informado)
   * Código: 102300 | FILE PEITO CUBOS TEMP CG NATTO 600G MOSTARDA E MEL (Cód. Interno: não informado)
   * Código: 20723  | FILE PEITO FGO C ASSA F SEARA 800G (Cód. Interno: não informado)
   * Código: 98986  | FILE PEITO FGO CANCAO BDJ 1KG (Cód. Interno: não informado)
   * Código: 9589   | FILE PEITO FGO CG AURORA BD 1KG (Cód. Interno: não informado)
   * Código: 37000  | FILE PEITO FGO CG CORTE SADIA BD1KG (Cód. Interno: não informado)
   * Código: 11776  | FILE PEITO FGO CG CUB MAURICEA 400G (Cód. Interno: não informado)
   * Código: 11781  | FILE PEITO FGO CG CUB MAURICEA 400G ERVA FINAS (Cód. Interno: não informado)
   * Código: 11778  | FILE PEITO FGO CG CUB MAURICEA 400G TEMP 4 QJO (Cód. Interno: não informado)
   * Código: 34231  | FILE PEITO FGO CG CUB NATTO 400G BARBECUE (Cód. Interno: não informado)
   * Código: 28028  | FILE PEITO FGO CG GUIBON KG (Cód. Interno: 3126)
   * Código: 20751  | FILE PEITO FGO CG IQF SEARA 1KG (Cód. Interno: não informado)
   * Código: 20250  | FILE PEITO FGO CG MAURICEA BD1KG (Cód. Interno: não informado)
   * Código: 22699  | FILE PEITO FGO CG NATTO BD1KG (Cód. Interno: não informado)
   * Código: 22864  | FILE PEITO FGO CG NATTO IND KG (Cód. Interno: 2733)
   * Código: 19628  | FILE PEITO FGO CG PERDIGAO 800G (Cód. Interno: não informado)
   * Código: 19632  | FILE PEITO FGO CG SADIA BD1KG (Cód. Interno: não informado)
   * Código: 30592  | FILE PEITO FGO CG SADIA BIO BD 1KG (Cód. Interno: não informado)
   * Código: 19631  | FILE PEITO FGO CG SADIA PCT1KG (Cód. Interno: não informado)
   * Código: 20747  | FILE PEITO FGO CG SEARA BD1KG (Cód. Interno: não informado)
   * Código: 101413 | FILE PEITO FGO DESF TEMP NATTO 400G (Cód. Interno: não informado)
   * Código: 101416 | FILE PEITO FGO TIRA TEMP NATTO 400G (Cód. Interno: não informado)
   * Código: 50867  | FILEZ FGO EMP MAURICEA PCT 700G (Cód. Interno: não informado)
   * Código: 27369  | FILEZIN EMPANADO NATTO FGO CG 700G (Cód. Interno: não informado)
   * Código: 59046  | FILEZINHO DE FRANGO NATTO EMP CROC 700G (Cód. Interno: não informado)
   * Código: 19637  | FILEZINHO FGO CG PERDIGAO BD1KG (Cód. Interno: não informado)
   * Código: 20748  | FILEZINHO FGO CG SEARA BD1KG (Cód. Interno: não informado)
   * Código: 9599   | FILEZINHO FGO CONG AURORA BD1KG (Cód. Interno: não informado)
   * Código: 19629  | FILEZINHO FGO CONG PERDIGAO PCT800G (Cód. Interno: não informado)
   * Código: 19633  | FILEZINHO FGO CONG SADIA BD1KG (Cód. Interno: não informado)
   * Código: 102291 | FILEZINHO FGO GRE TEM CG NATTO 700G (Cód. Interno: não informado)
   * Código: 19630  | FILEZINHO FGO IQF CONG SADIA PCT1KG (Cód. Interno: não informado)
   * Código: 20749  | FILEZINHO FGO IQF CONG SEARA PCT1KG (Cód. Interno: não informado)
   * Código: 97630  | FILEZINHO FGO SASSAMI CG GUIBON 1KG (Cód. Interno: não informado)
   * Código: 52626  | FILEZINHO SASSAM FRANGO FORMOSO 1KG (Cód. Interno: não informado)
   * Código: 79039  | FILEZINHO SASSAMI CANCAO IQF 1KG (Cód. Interno: não informado)
   * Código: 31841  | FILEZINHO SASSAMI NATTO CONG BD 1KG (Cód. Interno: não informado)
   * Código: 53547  | FRANGO CONG CAIPIRA NHO BENTO KG (Cód. Interno: 65)
   * Código: 52600  | FRANGO INTEIRO CONG FORMOSO KG (Cód. Interno: 524313)
   * Código: 34239  | FRANGO MINI TEMP CG NATTO KG (Cód. Interno: 34239)
   * Código: 27424  | GALINHA INT CG SOMAVE KG (Cód. Interno: 3077)
   * Código: 37207  | ISCAS FGO EMPAN CG SEARA APIM 300G (Cód. Interno: não informado)
   * Código: 34106  | LING FGO CG MAURICEA PCT 600G (Cód. Interno: não informado)
   * Código: 11715  | LING FGO CONG MAURICEA PCT 3KG (Cód. Interno: não informado)
   * Código: 9938   | LING FGO GRILL CONG NATTO 600G BACON (Cód. Interno: não informado)
   * Código: 9962   | LING FGO GRILL CONG NATTO 600G PIM (Cód. Interno: não informado)
   * Código: 9955   | LING FGO GRILL CONG NATTO 600G QJO (Cód. Interno: não informado)
   * Código: 63878  | LING FGO PERDIGAO NABRASA 700G (Cód. Interno: não informado)
   * Código: 20101  | LING FGO SADIA 5KG (Cód. Interno: não informado)
   * Código: 63881  | LING FGO SADIA 700G (Cód. Interno: não informado)
   * Código: 18333  | LING FGO SEARA 5KG (Cód. Interno: 7027)
   * Código: 9358   | LING FRANGO CG AURORA PCT5KG (Cód. Interno: não informado)
   * Código: 9960   | LING TOSC CONG FGO NATTO 600G (Cód. Interno: não informado)
   * Código: 10030  | LING TOSC FGO CG FGO NATTO 3KG (Cód. Interno: não informado)
   * Código: 49417  | LINGUICA DE FRANGO AURORA 700G (Cód. Interno: não informado)
   * Código: 34234  | MEIO ASA FGO CG NATTO 600G BARBECUE (Cód. Interno: não informado)
   * Código: 11871  | MEIO ASAS FGO IQF MAURICEA 1KG (Cód. Interno: não informado)
   * Código: 19613  | MEIO DA ASA FGO IQF SADIA PCT 1KG (Cód. Interno: não informado)
   * Código: 102160 | MEIO DA ASA TULIPA NABRASA 800G ALHO E ERVAS (Cód. Interno: não informado)
   * Código: 102159 | MEIO DA ASA TULIPA NABRASA 800GR (Cód. Interno: não informado)
   * Código: 97645  | MOELA FRANGO CONG GUIBON SC 1KG (Cód. Interno: não informado)
   * Código: 22703  | PEITO FGO CG NATTO BD1KG (Cód. Interno: não informado)
   * Código: 20264  | PEITO FGO CONG MAURICEA IND KG (Cód. Interno: 2003)
   * Código: 22862  | PEITO FGO CONG NATTO IND KG (Cód. Interno: 2731)
   * Código: 37016  | PEITO FGO TEMP DESF CG SADIA 400G (Cód. Interno: não informado)
   * Código: 34235  | SOBCOX DESOS FGO CG NATTO 600G CHIMICHURRI (Cód. Interno: não informado)
   * Código: 19655  | SOBCOX FGO CG ASSA F SADIA 800G (Cód. Interno: não informado)
   * Código: 20724  | SOBCOX FGO CG ASSA F SEARA 800G (Cód. Interno: não informado)
   * Código: 19653  | SOBCOX FGO CG SADIA 1KG (Cód. Interno: não informado)
   * Código: 37995  | SOBRECOXA FGO CG DES SEARA CHIM800G (Cód. Interno: não informado)
   * Código: 37992  | SOBRECOXA FGO CG SEARA BD 1KG (Cód. Interno: não informado)
   * Código: 52625  | SOBRECOXA FRANGO FORMOSO CONG 1KG (Cód. Interno: não informado)

   Aves Resfriadas:
   * Código: 34272  | ASA FGO RESF MAURICEA KG (Cód. Interno: não informado)
   * Código: 10008  | ASA FGO RESF NATTO BD700G (Cód. Interno: não informado)
   * Código: 49073  | ASA FGO RESF NATTO KG (Cód. Interno: 49073)
   * Código: 49075  | COXA C SOB FGO NATTO RESF KG (Cód. Interno: 49075)
   * Código: 34274  | COXA C SOB FGO RESF MAURICEA KG (Cód. Interno: 34274)
   * Código: 34279  | COXA FGO RESF MAURICEA KG (Cód. Interno: 34279)
   * Código: 12156  | COXASOB FGO C PELE MAURICEA BD700G RF DESOS (Cód. Interno: não informado)
   * Código: 11817  | COXIN ASA FGO CG TEMP MAURICEA500G A VACUO (Cód. Interno: não informado)
   * Código: 11914  | FGO INT RESF MAURICEA KG (Cód. Interno: 1190)
   * Código: 10013  | FGO INT RESF NATTO KG (Cód. Interno: 1068)
   * Código: 11796  | FGO PASSARIN CGTEMP MAURICEA VC500G (Cód. Interno: não informado)
   * Código: 34282  | FIGADO FGO RESF MAURICEA KG (Cód. Interno: não informado)
   * Código: 34284  | FILE PEITO FGO RESF MAURICEA KG (Cód. Interno: 34284)
   * Código: 9986   | FILE PEITO FGO RESF NATTO 700G (Cód. Interno: não informado)
   * Código: 9997   | FILE SOBRECOX FGO RESF NATTO BD700G (Cód. Interno: não informado)
   * Código: 12010  | FILEZINHO FGO RESF MAURICEA BD700G (Cód. Interno: não informado)
   * Código: 20053  | LING FGO RESF MAURICEA KG (Cód. Interno: 1949)
   * Código: 20398  | LING FGO SEARA KG (Cód. Interno: 2034)
   * Código: 20395  | LING TOSC FGO RESF NATTO KG (Cód. Interno: 2032)
   * Código: 10012  | MOELA FGO RF NATTO BD500G (Cód. Interno: não informado)
   * Código: 43084  | PE GALINHA RESF KG (Cód. Interno: 43084)
   * Código: 67925  | PEITO CANCAO ENV KG (Cód. Interno: 538980)
   * Código: 49078  | PEITO FGO NATTO RESF KG (Cód. Interno: 49078)
   * Código: 34287  | PEITO FGO RESF MAURICEA KG (Cód. Interno: 34287)
   * Código: 11535  | PEITO FGO S PELE MAURICEA BD700G RESF (Cód. Interno: não informado)
   * Código: 11736  | PERTENC FGO CANJA CG MAURICEA KG (Cód. Interno: 1189)
   * Código: 11815  | SOBCOX DESOS CG MAURICEA 500G TEMP (Cód. Interno: não informado)
   * Código: 49076  | SOBCOX FGO NATTO RESF KG (Cód. Interno: 49076)
   * Código: 34288  | SOBCOX FGO RESF MAURICEA KG (Cód. Interno: 34288)
   * Código: 9999   | SOBCOX FGO RF NATTO S PELE 700G (Cód. Interno: não informado)

--------------------------------------------------------------------------------
2. PESCADOS
--------------------------------------------------------------------------------

   Pescados Congelados:
   * Código: 16304  | ATUM POSTA FISH 1KG (Cód. Interno: não informado)
   * Código: 42161  | BOLINHO BACALH CG NORONHA 300G (Cód. Interno: não informado)
   * Código: 22964  | BOLINHO BACALH COQ TIA ELIANA 1KG (Cód. Interno: não informado)
   * Código: 51510  | CAMAR CG CINZA QUALIMAR 25 35 300G DESC EVISC COZ (Cód. Interno: não informado)
   * Código: 49356  | CAMAR CG CINZA QUALIMAR 50 80 300G (Cód. Interno: não informado)
   * Código: 97538  | CAMAR CIN MAZZA FOOD S CAB COZ 200G (Cód. Interno: não informado)
   * Código: 97536  | CAMAR CIN MAZZA FOODS DESC COZ 350G (Cód. Interno: não informado)
   * Código: 97539  | CAMAR CIN MAZZA FOODS FRITO CG 300G (Cód. Interno: não informado)
   * Código: 97537  | CAMAR CIN MAZZA FOODS INT COZ 200G (Cód. Interno: não informado)
   * Código: 97556  | CAMAR EMP JUMBO CG QUALIMAR 300G (Cód. Interno: não informado)
   * Código: 97553  | CAMAR INT15 24 CG COZ QUALIMAR 180G (Cód. Interno: não informado)
   * Código: 37037  | CAMAR S CAB 71 90 CG MAURICEA 400G (Cód. Interno: não informado)
   * Código: 75297  | CAMARAO CINZA EMPANADO IQF 300G (Cód. Interno: não informado)
   * Código: 49878  | CAMARAO CINZA MS CAB CG NATTO 400G (Cód. Interno: não informado)
   * Código: 98491  | CAMARAO CZ QUAL DESC EV 35 55 300G (Cód. Interno: não informado)
   * Código: 81145  | CAMARAO DESC 30 45 200G HA (Cód. Interno: não informado)
   * Código: 49875  | CAMARAO EMPANADO CG NATTO PCT 300G (Cód. Interno: não informado)
   * Código: 53219  | CAMARAO INT 80 120 IQF KG (Cód. Interno: 53219)
   * Código: 97937  | CAMARAO QUALIMAR CZ CG 30 50 180G (Cód. Interno: não informado)
   * Código: 58616  | CARNE MOIDA BRAZILIAN FISH TILAPIA 500G (Cód. Interno: não informado)
   * Código: 21647  | CORVINA INT CG KG (Cód. Interno: 2440)
   * Código: 16271  | CORVINA INT FISH EMB KG (Cód. Interno: 1271)
   * Código: 42072  | CUBO PEIXE TILAP MASTERBOI PCT 500G (Cód. Interno: não informado)
   * Código: 31220  | FILE CAMARAO COZ MASTERBOI 400G (Cód. Interno: não informado)
   * Código: 102117 | FILE DE MERLUZA SEARA 500G (Cód. Interno: não informado)
   * Código: 58217  | FILE DE TILAPIA BRAZILIAN FISH CG 500G (Cód. Interno: não informado)
   * Código: 58136  | FILE DE TILAPIA CONG BRAZ FISH 250G (Cód. Interno: não informado)
   * Código: 102116 | FILE DE TILAPIA SEARA 600G (Cód. Interno: não informado)
   * Código: 33912  | FILE DOURADO CG FISH PCT 800G (Cód. Interno: não informado)
   * Código: 16321  | FILE MERLUZA FISH 800G (Cód. Interno: não informado)
   * Código: 32585  | FILE MERLUZA NORONHA CG IMP 500G (Cód. Interno: não informado)
   * Código: 37551  | FILE MERLUZA NORONHA EMP CG PCT500G (Cód. Interno: não informado)
   * Código: 16324  | FILE PESC FISH 800G (Cód. Interno: não informado)
   * Código: 33914  | FILE PIRAMUTABA CG FISH PCT 800G (Cód. Interno: não informado)
   * Código: 38097  | FILE POLACA CG NATTO PCT 800G (Cód. Interno: não informado)
   * Código: 91496  | FILE SALMAO CONG CP SEARA 500G (Cód. Interno: não informado)
   * Código: 32590  | FILE SALMAO NORONHA CG PED 500G (Cód. Interno: não informado)
   * Código: 63854  | FILE TILAPIA CG MAZZA FOODS 400G (Cód. Interno: não informado)
   * Código: 63853  | FILE TILAPIA CG MAZZA FOODS 800G (Cód. Interno: não informado)
   * Código: 27370  | FILE TILAPIA CG NATTO PCT 400G (Cód. Interno: não informado)
   * Código: 47700  | FILE TILAPIA CG NATTO PCT 800G (Cód. Interno: não informado)
   * Código: 20938  | FILE TILAPIA CG NETUNO 500G (Cód. Interno: não informado)
   * Código: 34834  | FILE TILAPIA CG QUALIMAR PCT 400G (Cód. Interno: não informado)
   * Código: 16322  | FILE TILAPIA CONG FISH 800G (Cód. Interno: não informado)
   * Código: 31448  | FILE TILAPIA EMP CG NATTO PCT 500G (Cód. Interno: não informado)
   * Código: 76495  | FILE TILAPIA SEARA EMPANADA IQF 400 G (Cód. Interno: não informado)
   * Código: 33910  | FILE URITINGA CG FISH PCT 800G (Cód. Interno: não informado)
   * Código: 63206  | ISCA DE TILAPIA CG BRAZ FISH 300G (Cód. Interno: não informado)
   * Código: 37550  | KANI KAMA NORONHA PCT 250G (Cód. Interno: não informado)
   * Código: 51999  | PEIXE CASTANHA EVISC S.CAB CONG KG (Cód. Interno: 7675)
   * Código: 63882  | POLACA MAZZA SALG DESF 500G (Cód. Interno: não informado)
   * Código: 50189  | POLACA SECA SALG DESF SEAPRO 500G (Cód. Interno: não informado)
   * Código: 16306  | POSTA CORVINA FISH 1KG (Cód. Interno: não informado)
   * Código: 32588  | POSTA CORVINA NORONHA CG PCT 1KG (Cód. Interno: não informado)
   * Código: 16310  | POSTA DE DOURADO CG FISH 1KG (Cód. Interno: não informado)
   * Código: 16311  | POSTA DE ESPADA FISH 1KG (Cód. Interno: não informado)
   * Código: 33798  | POSTA DE PESCADA CG QUALIMAR 500G (Cód. Interno: não informado)
   * Código: 47283  | POSTA DOURADA MASTERBOI C PELE 800G (Cód. Interno: não informado)
   * Código: 47124  | POSTA PIRAMUTAB MASTERBOI PELE 800G (Cód. Interno: não informado)
   * Código: 16317  | POSTA PIRAMUTABA FISH 1KG (Cód. Interno: não informado)
   * Código: 16319  | POSTA TILAPIA FISH 800G (Cód. Interno: não informado)
   * Código: 98832  | STEAK TILAPIA BRAZ FISH CG 100G (Cód. Interno: não informado)
   * Código: 76496  | TIRINHA PEIXE SEARA EMPANADA IQF 30 0G (Cód. Interno: não informado)
   * Código: 38096  | TIRINHAS POLACA EMP CG NATTO 300G (Cód. Interno: não informado)

   Pescados Resfriados:
   * Código: 21430  | BACALHAU RESF SAITHE KG (Cód. Interno: 2355)
   * Código: 53304  | BACALHAU SAITHE 10 12 KG (Cód. Interno: 53304)
   * Código: 52014  | FILE MERLUZA ALASCA KG (Cód. Interno: 15903)
   * Código: 96726  | PEIXE ATUM EM POSTAS KG (Cód. Interno: 96726)
   * Código: 16291  | PEIXE CAST EVISC FISH 1KG (Cód. Interno: não informado)
   * Código: 16266  | PEIXE CAVALINHA INT FISH 1KG (Cód. Interno: não informado)
   * Código: 96727  | PEIXE CORVINA EM POSTAS KG (Cód. Interno: 96727)
   * Código: 96728  | PEIXE DOURADO EM POSTAS KG (Cód. Interno: 96728)
   * Código: 16297  | PEIXE PESCADA EVISC FISH 1KG (Cód. Interno: não informado)
   * Código: 16277  | PEIXE SARDINHA FISH INT 1KG (Cód. Interno: não informado)
   * Código: 52000  | PEIXE SARDINHA S CAB ESVICERADA KG (Cód. Interno: 7702)
   * Código: 16318  | PEIXE SERRA EM POSTA FISH 1KG (Cód. Interno: não informado)
   * Código: 16281  | PEIXE TAINHA INT FISH EMB KG (Cód. Interno: 1272)
   * Código: 52987  | PEIXE TAINHA KG (Cód. Interno: 52987)
   * Código: 52974  | PEIXE TILAPI KG (Cód. Interno: 52974)

--------------------------------------------------------------------------------
3. SUÍNOS
--------------------------------------------------------------------------------

   * Código: 19666  | ALCATRA SUINA CG SADIA KG (Cód. Interno: 1805)
   * Código: 49268  | ALCATRA SUINA CG TEMP SUINCO PCT KG (Cód. Interno: 49268)
   * Código: 37458  | BARRIGA SUINA CG TEMP SAUDALI KG (Cód. Interno: 37458)
   * Código: 36998  | BISTECA SUINA CG SADIA 800G (Cód. Interno: não informado)
   * Código: 28266  | CARCACA SUINA PC KG (Cód. Interno: 3132)
   * Código: 20916  | CARRE SUINO CG INT KG (Cód. Interno: 2257)
   * Código: 37459  | COST GRILL SUINA CG TEMP SAUDALI KG (Cód. Interno: 37459)
   * Código: 20309  | COSTELA SUINA BBQ SEARA GOURMET 1KG (Cód. Interno: não informado)
   * Código: 49276  | COSTELA SUINA CG TEMP SUINCO PCT KG (Cód. Interno: 49276)
   * Código: 19674  | COSTELA SUINA CONG NABRASA KG (Cód. Interno: 1811)
   * Código: 19673  | COSTELA SUINA CONG PERDIGAO KG (Cód. Interno: 2267)
   * Código: 30494  | COSTELA TIRAS SUINA CG SADIA KG (Cód. Interno: 3319)
   * Código: 37462  | COSTELA TIRAS SUINA CG SAUDALI KG (Cód. Interno: 37462)
   * Código: 49277  | COSTELINHA A PASSAR TEMP SUINCO 1KG (Cód. Interno: não informado)
   * Código: 19310  | COSTELINHA GRILL SAUDALI KG (Cód. Interno: 1954)
   * Código: 19320  | COSTELINHA SUI TEMP CONG SAUDALI KG (Cód. Interno: 1751)
   * Código: 19683  | COXAO MOLE SUINO CONG SADIA KG (Cód. Interno: 1818)
   * Código: 36992  | FILE MIGNON SUI FAT CG SADIA 800G (Cód. Interno: não informado)
   * Código: 49261  | LING PERNIL CG SUINCO C BACON 600G (Cód. Interno: não informado)
   * Código: 49262  | LING PERNIL CG SUINCO C PIMEN 600G (Cód. Interno: não informado)
   * Código: 49259  | LING PERNIL CG SUINCO PCT 5KG (Cód. Interno: não informado)
   * Código: 63863  | LING PERNIL PERDIGAO NABRASA 700G (Cód. Interno: não informado)
   * Código: 25728  | LING SUINA CG AURORA CHURRA PCT700G (Cód. Interno: não informado)
   * Código: 9363   | LING SUINA CG AURORA CHURRAS PCT5KG (Cód. Interno: não informado)
   * Código: 50113  | LING SUINA CG CHURRASCO SADIA 700G (Cód. Interno: não informado)
   * Código: 19299  | LING SUINA CG SAUDALI 2,5KG (Cód. Interno: não informado)
   * Código: 18335  | LING SUINA CG SEARA 5KG (Cód. Interno: 89309)
   * Código: 49260  | LING SUINA CG SUINCO CHURRAS PCT5KG (Cód. Interno: não informado)
   * Código: 20421  | LING SUINA RESF SEARA KG (Cód. Interno: 2042)
   * Código: 20419  | LING TOSC SUINA RESF SAUDALI KG (Cód. Interno: 2040)
   * Código: 20102  | LING TOSC SUINA SADIA 5KG (Cód. Interno: não informado)
   * Código: 20310  | LOMBO BBQ SEARA GOURMET 1KG (Cód. Interno: não informado)
   * Código: 36993  | LOMBO SUI FAT CG SADIA 800G (Cód. Interno: não informado)
   * Código: 49274  | LOMBO SUINO CG TEMP SUINCO PCT KG (Cód. Interno: 49274)
   * Código: 37461  | LOMBO SUINO CONG SAUDALI KG (Cód. Interno: 37461)
   * Código: 30493  | LOMBO SUINO S OSSO CONG SADIA KG (Cód. Interno: 3318)
   * Código: 19667  | PANCETA SUINA CG TEMP NABRASA KG TOQUE LIMAO (Cód. Interno: 1806)
   * Código: 19685  | PATINHO SUINO CONG SADIA KG (Cód. Interno: 1820)
   * Código: 28274  | PE SUINO RF M ALLEGRE KG (Cód. Interno: 3144)
   * Código: 19684  | PERNIL SUINO CONG SADIA KG (Cód. Interno: 1819)
   * Código: 19686  | PICANHA SUINA CONG SADIA KG (Cód. Interno: 1821)
   * Código: 19675  | PONTA COST SUINA CONG SADIA KG (Cód. Interno: 1812)
   * Código: 28268  | SARAPATEL SUI RF M ALLEGRE PACOT KG (Cód. Interno: 28268)
   * Código: 19687  | SOBPALETA SUINA CONG SADIA KG (Cód. Interno: 1822)
   * Código: 36994  | SOBREPALETA SUI FAT CG SADIA 800G (Cód. Interno: não informado)
   * Código: 28271  | TRIPA SUINA RF MALLEGRE PACOTE KG (Cód. Interno: 28271)
"""

items = []
for line in text.splitlines():
    line = line.strip()
    if line.startswith("* Código:"):
        # Remove (Cód. Interno: não informado)
        line = line.replace(" (Cód. Interno: não informado)", "")
        
        # Replace * Código: with * PLU:
        line = line.replace("* Código:", "* PLU:")
        
        # Replace (Cód. Interno: with (Código de Balança:
        line = line.replace("(Cód. Interno:", "(Código de Balança:")
        
        # We need to extract the description to sort by it
        # Because we replaced * Código: with * PLU:
        match = re.search(r'\* PLU: \s*(\d+)\s*\|\s*(.*)', line)
        if match:
            code = match.group(1).strip()
            desc = match.group(2).strip()
            # if the desc still has a cod interno at the end, we can ignore it for sorting or strip it
            desc_for_sort = desc.split("(Código de")[0].strip()
            items.append({"code": code, "desc": desc_for_sort, "raw": line})

# Sort alphabetically by description
items_sorted = sorted(items, key=lambda x: x["desc"])

with open("lista_ordenada.md", "w", encoding="utf-8") as f:
    f.write("# Lista de Produtos Ordenada Alfabeticamente\n\n")
    for item in items_sorted:
        f.write(f"{item['raw']}\n")

print("Generated lista_ordenada.md")
